// src/pages/suppliers/formContainer.jsx
import React from 'react';

// Icons (using your existing icons)
import IconFactory from '../../../components/Icon/IconBuilding';
import IconTools from '../../../components/Icon/IconCpuBolt';
import IconChecklist from '../../../components/Icon/IconChecks';
import IconShield from '../../../components/Icon/IconShield';
import IconScale from '../../../components/Icon/IconChartBar';
import IconDocument from '../../../components/Icon/IconFile';

// Modern responsive grid configuration
const getModernGrid = (cols) => {
    return {
        base: 'grid-cols-1',
        sm: 'sm:grid-cols-2',
        md: `md:grid-cols-${Math.min(cols, 2)}`,
        lg: `lg:grid-cols-${Math.min(cols, 3)}`,
        xl: `xl:grid-cols-${cols}`,
    };
};

// Modern field styling with accent colors
const getFieldStyle = (span, type = 'default') => {
    const styles = {
        default: 'border-gray-300 focus:border-blue-500 focus:ring-blue-500',
        success: 'border-emerald-300 focus:border-emerald-500 focus:ring-emerald-500',
        warning: 'border-amber-300 focus:border-amber-500 focus:ring-amber-500',
        error: 'border-rose-300 focus:border-rose-500 focus:ring-rose-500',
    };

    return {
        container: `col-span-${span} space-y-2`,
        input: `w-full px-4 py-3 rounded-lg border ${styles[type]} focus:ring-2 focus:ring-opacity-20 transition-all duration-200 text-sm placeholder:text-gray-400 bg-white`,
        label: 'block text-sm font-semibold text-gray-700 flex items-center gap-2',
        helpText: 'text-xs text-gray-500 mt-1',
    };
};

// Helper function for responsive classes
const responsiveClass = (breakpoints) => {
    return Object.values(breakpoints).join(' ');
};

// Modern Supplier Tabs Configuration
const supplierTabs = [
    {
        label: 'Supplier Profile',
        name: 'supplierProfile',
        icon: <IconFactory className="w-5 h-5 text-blue-600" />,
        iconColor: 'blue',
        accordianStyle: responsiveClass(getModernGrid(2)),
        activeKey: 'supplierProfile',
        children: [
            {
                title: 'Basic Information',
                subtitle: 'Primary details about the supplier',
                icon: '🏢',
                formFields: [
                    {
                        label: 'Supplier Name',
                        name: 'supplier_name',
                        inputType: 'text',
                        placeholder: 'Enter full supplier name',
                        require: true,
                        classStyle: 'col-span-2',
                        fieldStyle: getFieldStyle(2, 'default'),
                        validation: {
                            required: 'Supplier name is required',
                            minLength: { value: 3, message: 'Must be at least 3 characters' },
                        },
                        icon: '🏷️',
                        helpText: 'Official registered name of the supplier',
                    },
                    {
                        label: 'Category',
                        name: 'category',
                        inputType: 'select',
                        optionList: 'supplierCategories',
                        displayKey: 'label',
                        uniqueKey: 'value',
                        require: true,
                        classStyle: 'col-span-1',
                        fieldStyle: getFieldStyle(1, 'default'),
                        validation: { required: 'Category is required' },
                        icon: '📋',
                        helpText: 'Select primary business category',
                    },
                    {
                        label: 'Supplier Code',
                        name: 'supplier_code',
                        inputType: 'text',
                        placeholder: 'SUP-001',
                        require: false,
                        classStyle: 'col-span-1',
                        fieldStyle: getFieldStyle(1, 'success'),
                        icon: '🔢',
                        helpText: 'Internal reference code',
                    },
                    {
                        label: 'Address',
                        name: 'address',
                        inputType: 'textarea',
                        placeholder: 'Complete business address',
                        require: true,
                        rows: 3,
                        classStyle: 'col-span-2',
                        fieldStyle: getFieldStyle(2, 'default'),
                        validation: {
                            required: 'Address is required',
                            minLength: { value: 10, message: 'Must be at least 10 characters' },
                        },
                        icon: '📍',
                        helpText: 'Full registered business address',
                    },
                    {
                        label: 'City',
                        name: 'city',
                        inputType: 'text',
                        placeholder: 'City name',
                        require: true,
                        classStyle: 'col-span-1',
                        fieldStyle: getFieldStyle(1, 'default'),
                        validation: { required: 'City is required' },
                        icon: '🏙️',
                    },
                    {
                        label: 'Postal/ZIP Code',
                        name: 'postal_code',
                        inputType: 'text',
                        placeholder: '600001',
                        require: true,
                        classStyle: 'col-span-1',
                        fieldStyle: getFieldStyle(1, 'default'),
                        mask: '999999',
                        validation: {
                            required: 'Postal code is required',
                            validate: (value) => {
                                const cleaned = value?.replace(/\D/g, '') || '';
                                return cleaned.length === 6 || 'Must be exactly 6 digits';
                            },
                        },
                        icon: '📮',
                    },
                    {
                        label: 'Landmark',
                        name: 'landmark',
                        inputType: 'text',
                        placeholder: 'Nearest landmark',
                        require: false,
                        classStyle: 'col-span-2',
                        fieldStyle: getFieldStyle(2, 'default'),
                        icon: '🗺️',
                        helpText: 'Helpful for location identification',
                    },
                    {
                        label: 'Year of Establishment',
                        name: 'year_of_establishment',
                        inputType: 'number',
                        placeholder: 'YYYY',
                        require: true,
                        classStyle: 'col-span-1',
                        fieldStyle: getFieldStyle(1, 'warning'),
                        validation: {
                            required: 'Year of establishment is required',
                            min: { value: 1900, message: 'Must be valid year' },
                            max: { value: new Date().getFullYear(), message: 'Cannot be future year' },
                        },
                        icon: '📅',
                    },
                    {
                        label: 'GPS Coordinates',
                        name: 'gps_coordinates',
                        inputType: 'text',
                        placeholder: '12.9716° N, 77.5946° E',
                        require: false,
                        classStyle: 'col-span-1',
                        fieldStyle: getFieldStyle(1, 'default'),
                        icon: '🎯',
                        helpText: 'Latitude, Longitude format',
                    },
                ],
            },
            {
                title: 'Contact Information',
                subtitle: 'Primary contact details',
                icon: '📞',
                formFields: [
                    {
                        label: 'Contact Person',
                        name: 'contact_person_name',
                        inputType: 'text',
                        placeholder: 'Full name of contact person',
                        require: true,
                        classStyle: 'col-span-1',
                        fieldStyle: getFieldStyle(1, 'default'),
                        validation: {
                            required: 'Contact person is required',
                            minLength: { value: 3, message: 'Must be at least 3 characters' },
                        },
                        icon: '👤',
                    },
                    {
                        label: 'Designation',
                        name: 'designation',
                        inputType: 'text',
                        placeholder: 'Position in company',
                        require: true,
                        classStyle: 'col-span-1',
                        fieldStyle: getFieldStyle(1, 'default'),
                        validation: { required: 'Designation is required' },
                        icon: '💼',
                    },
                    {
                        label: 'Mobile Number',
                        name: 'mobile_number',
                        inputType: 'text',
                        placeholder: '10-digit mobile number',
                        require: true,
                        classStyle: 'col-span-1',
                        fieldStyle: getFieldStyle(1, 'success'),
                        mask: '9999 9999 99',
                        validation: {
                            required: 'Mobile number is required',
                            validate: (value) => {
                                const cleaned = value?.replace(/\D/g, '') || '';
                                return cleaned.length === 10 || 'Must be exactly 10 digits';
                            },
                        },
                        icon: '📱',
                    },
                    {
                        label: 'Landline',
                        name: 'landline',
                        inputType: 'text',
                        placeholder: 'Landline with STD code',
                        require: false,
                        classStyle: 'col-span-1',
                        fieldStyle: getFieldStyle(1, 'default'),
                        icon: '☎️',
                    },
                    {
                        label: 'Email Address',
                        name: 'email',
                        inputType: 'email',
                        placeholder: 'official@email.com',
                        require: false,
                        classStyle: 'col-span-2',
                        fieldStyle: getFieldStyle(2, 'default'),
                        icon: '📧',
                    },
                ],
            },
            {
                title: 'Business Information',
                subtitle: 'Company structure and financial details',
                icon: '💼',
                formFields: [
                    {
                        label: 'Factory Owner Name',
                        name: 'factory_owner_name',
                        inputType: 'text',
                        placeholder: 'Owner/Director name',
                        require: true,
                        classStyle: 'col-span-1',
                        fieldStyle: getFieldStyle(1, 'default'),
                        validation: {
                            required: 'Factory owner name is required',
                            minLength: { value: 3, message: 'Must be at least 3 characters' },
                        },
                        icon: '👑',
                    },
                    {
                        label: 'Business Start Date with ASIAN',
                        name: 'business_start_date',
                        inputType: 'date',
                        require: false,
                        classStyle: 'col-span-1',
                        fieldStyle: getFieldStyle(1, 'warning'),
                        icon: '🤝',
                    },
                    {
                        label: 'Ownership Type',
                        name: 'ownership_type',
                        inputType: 'select',
                        optionList: 'ownershipTypes',
                        displayKey: 'label',
                        uniqueKey: 'value',
                        require: true,
                        classStyle: 'col-span-1',
                        fieldStyle: getFieldStyle(1, 'default'),
                        validation: { required: 'Ownership type is required' },
                        icon: '🏛️',
                    },
                    {
                        label: 'Joint Venture Name',
                        name: 'joint_venture_name',
                        inputType: 'text',
                        placeholder: 'If applicable',
                        require: false,
                        classStyle: 'col-span-1',
                        fieldStyle: getFieldStyle(1, 'default'),
                        condition: (state) => state.ownership_type === 'joint_venture',
                        icon: '🤝',
                    },
                    {
                        label: 'Annual Turnover (₹)',
                        name: 'annual_turnover',
                        inputType: 'number',
                        placeholder: 'Annual turnover in rupees',
                        require: false,
                        classStyle: 'col-span-1',
                        fieldStyle: getFieldStyle(1, 'success'),
                        min: 0,
                        icon: '💰',
                    },
                    {
                        label: 'Direct Business with Customers',
                        name: 'direct_business',
                        inputType: 'checkbox',
                        require: false,
                        classStyle: 'col-span-1',
                        fieldStyle: getFieldStyle(1, 'default'),
                        icon: '🎯',
                    },
                    {
                        label: 'Customer Names',
                        name: 'customer_names',
                        inputType: 'textarea',
                        placeholder: 'List major customers if direct business',
                        require: false,
                        rows: 2,
                        classStyle: 'col-span-2',
                        fieldStyle: getFieldStyle(2, 'default'),
                        condition: (state) => state.direct_business,
                        icon: '👥',
                    },
                ],
            },
            {
                title: 'Bank Account Details',
                subtitle: 'Financial and tax information',
                icon: '🏦',
                formFields: [
                    {
                        label: 'Account Name',
                        name: 'account_name',
                        inputType: 'text',
                        placeholder: 'Bank account holder name',
                        require: true,
                        classStyle: 'col-span-2',
                        fieldStyle: getFieldStyle(2, 'default'),
                        validation: {
                            required: 'Account name is required',
                            minLength: { value: 3, message: 'Must be at least 3 characters' },
                        },
                        icon: '👤',
                    },
                    {
                        label: 'Bank & Place',
                        name: 'bank_and_place',
                        inputType: 'text',
                        placeholder: 'Bank name and branch location',
                        require: true,
                        classStyle: 'col-span-2',
                        fieldStyle: getFieldStyle(2, 'default'),
                        validation: {
                            required: 'Bank & place is required',
                            minLength: { value: 3, message: 'Must be at least 3 characters' },
                        },
                        icon: '📍',
                    },
                    {
                        label: 'Account Number',
                        name: 'account_number',
                        inputType: 'text',
                        placeholder: 'Bank account number',
                        require: true,
                        classStyle: 'col-span-1',
                        fieldStyle: getFieldStyle(1, 'default'),
                        validation: {
                            required: 'Account number is required',
                            validate: (value) => {
                                const cleaned = value?.replace(/\D/g, '') || '';
                                return (cleaned.length >= 8 && cleaned.length <= 20) || 'Must be between 8 and 20 digits';
                            },
                        },
                        icon: '🔢',
                    },
                    {
                        label: 'IFSC/MICR Code',
                        name: 'ifsc_micr',
                        inputType: 'text',
                        placeholder: 'IFSC or MICR code',
                        require: true,
                        classStyle: 'col-span-1',
                        fieldStyle: getFieldStyle(1, 'default'),
                        validation: {
                            required: 'IFSC/MICR code is required',
                            minLength: { value: 11, message: 'IFSC code must be 11 characters' },
                        },
                        icon: '🏷️',
                    },
                    {
                        label: 'PAN Number',
                        name: 'pan_number',
                        inputType: 'text',
                        placeholder: 'Permanent Account Number',
                        require: true,
                        classStyle: 'col-span-1',
                        fieldStyle: getFieldStyle(1, 'success'),
                        validation: {
                            required: 'PAN number is required',
                            pattern: {
                                value: /^[A-Z]{5}[0-9]{4}[A-Z]{1}$/,
                                message: 'Invalid PAN format (e.g., ABCDE1234F)',
                            },
                        },
                        icon: '📋',
                    },
                    {
                        label: 'TAN Number',
                        name: 'tan_number',
                        inputType: 'text',
                        placeholder: 'Tax Deduction Account Number',
                        require: false,
                        classStyle: 'col-span-1',
                        fieldStyle: getFieldStyle(1, 'default'),
                        icon: '📋',
                    },
                    {
                        label: 'GSTIN Number',
                        name: 'gstin_number',
                        inputType: 'text',
                        placeholder: 'GST Identification Number',
                        require: true,
                        classStyle: 'col-span-2',
                        fieldStyle: getFieldStyle(2, 'warning'),
                        validation: {
                            required: 'GSTIN number is required',
                            pattern: {
                                value: /^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$/,
                                message: 'Invalid GSTIN format',
                            },
                        },
                        icon: '🏛️',
                    },
                ],
            },
        ],
    },
    {
        label: 'Machinery & Capacity',
        name: 'machineryCapacity',
        icon: <IconTools />,
        accordianStyle: 'grid lg:grid-cols-2 grid-cols-1 gap-6',
        children: [
            {
                title: 'Machinery Details (Add Multiple)',
                formFields: [
                    {
                        label: 'Machinery Details',
                        name: 'machinery_details',
                        inputType: 'multiAdd',
                        fields: [
                            {
                                label: 'Type of Machinery',
                                name: 'machinery_type',
                                inputType: 'select',
                                optionList: 'machineryTypes',
                                displayKey: 'label',
                                uniqueKey: 'value',
                                require: true,
                            },
                            {
                                label: 'Number of Machines',
                                name: 'number_of_machines',
                                inputType: 'number',
                                placeholder: 'Count',
                                require: true,
                                min: 1,
                            },
                            {
                                label: 'Category',
                                name: 'category',
                                inputType: 'text',
                                placeholder: 'Machine category',
                                require: false,
                            },
                        ],
                        require: true,
                        classStyle: 'col-span-2',
                    },
                ],
            },
            {
                title: 'Machine Categories',
                formFields: [
                    {
                        label: 'Machine Category',
                        name: 'machine_categories',
                        inputType: 'checkboxGroup',
                        options: [
                            { label: 'Hand Loom', value: 'hand_loom' },
                            { label: 'Power Loom', value: 'power_loom' },
                            { label: 'Auto Loom', value: 'auto_loom' },
                            { label: 'Dyeing', value: 'dyeing' },
                            { label: 'Printing', value: 'printing' },
                            { label: 'Others', value: 'others' },
                        ],
                        require: true,
                        classStyle: 'col-span-2',
                        validation: { required: 'Select at least one category' },
                    },
                    {
                        label: 'Specify Others',
                        name: 'other_machinery',
                        inputType: 'text',
                        placeholder: 'Specify other machinery types',
                        require: false,
                        classStyle: 'col-span-2',
                        condition: (state) => state.machine_categories?.includes('others'),
                    },
                ],
            },
            {
                title: 'Production Capacity',
                formFields: [
                    {
                        label: 'Article 1 Capacity',
                        name: 'article_1_capacity',
                        inputType: 'text',
                        placeholder: 'Capacity per day',
                        require: false,
                        classStyle: 'col-span-1',
                    },
                    {
                        label: 'Article 2 Capacity',
                        name: 'article_2_capacity',
                        inputType: 'text',
                        placeholder: 'Capacity per day',
                        require: false,
                        classStyle: 'col-span-1',
                    },
                    {
                        label: 'Article 3 Capacity',
                        name: 'article_3_capacity',
                        inputType: 'text',
                        placeholder: 'Capacity per day',
                        require: false,
                        classStyle: 'col-span-1',
                    },
                    {
                        label: 'Article 4 Capacity',
                        name: 'article_4_capacity',
                        inputType: 'text',
                        placeholder: 'Capacity per day',
                        require: false,
                        classStyle: 'col-span-1',
                    },
                    {
                        label: 'Total Per Day',
                        name: 'total_per_day',
                        inputType: 'text',
                        placeholder: 'e.g., 1000 Pcs, 5000 Mtrs, ₹100000',
                        require: true,
                        classStyle: 'col-span-1',
                        validation: { required: 'Total per day is required' },
                    },
                    {
                        label: 'Unit',
                        name: 'unit',
                        inputType: 'select',
                        optionList: 'capacityUnits',
                        displayKey: 'label',
                        uniqueKey: 'value',
                        require: true,
                        classStyle: 'col-span-1',
                        validation: { required: 'Unit is required' },
                    },
                    {
                        label: '% Share for ASIAN Articles',
                        name: 'asian_share_percentage',
                        inputType: 'number',
                        placeholder: 'Percentage',
                        require: false,
                        classStyle: 'col-span-1',
                        min: 0,
                        max: 100,
                        validation: {
                            validate: (value) => {
                                if (!value) return true;
                                return (value >= 0 && value <= 100) || 'Must be between 0 and 100';
                            },
                        },
                    },
                ],
            },
            {
                title: 'Manpower Details',
                formFields: [
                    {
                        label: 'Manpower Details',
                        name: 'manpower_details',
                        inputType: 'multiAdd',
                        fields: [
                            {
                                label: 'Category',
                                name: 'category',
                                inputType: 'text',
                                placeholder: 'e.g., S.A.P. / V.S. / Waxing Stamp',
                                require: false,
                            },
                            {
                                label: 'Male Count',
                                name: 'male_count',
                                inputType: 'number',
                                placeholder: 'Male employees',
                                require: false,
                                min: 0,
                            },
                            {
                                label: 'Female Count',
                                name: 'female_count',
                                inputType: 'number',
                                placeholder: 'Female employees',
                                require: false,
                                min: 0,
                            },
                            {
                                label: 'Total Numbers',
                                name: 'total_numbers',
                                inputType: 'number',
                                placeholder: 'Total employees',
                                require: true,
                                min: 0,
                            },
                        ],
                        require: false,
                        classStyle: 'col-span-2',
                    },
                ],
            },
            {
                title: 'Additional Workforce Info',
                formFields: [
                    {
                        label: 'Total Employees Strength',
                        name: 'total_employees_strength',
                        inputType: 'number',
                        placeholder: 'Total workforce',
                        require: true,
                        classStyle: 'col-span-1',
                        min: 0,
                        validation: { required: 'Total employees strength is required' },
                    },
                    {
                        label: 'Number of Migrant Workers',
                        name: 'migrant_workers_count',
                        inputType: 'number',
                        placeholder: 'Migrant workers count',
                        require: false,
                        classStyle: 'col-span-1',
                        min: 0,
                    },
                    {
                        label: 'Average Wages per Month (₹)',
                        name: 'average_wages',
                        inputType: 'number',
                        placeholder: 'Average monthly wages',
                        require: false,
                        classStyle: 'col-span-1',
                        min: 0,
                    },
                    {
                        label: 'Accident Insurance Number',
                        name: 'accident_insurance_number',
                        inputType: 'text',
                        placeholder: 'Insurance policy number',
                        require: false,
                        classStyle: 'col-span-1',
                    },
                ],
            },
        ],
    },
    {
        label: 'Operations & Shifts',
        name: 'operations',
        icon: <IconChecklist />,
        accordianStyle: 'grid lg:grid-cols-2 grid-cols-1 gap-6',
        children: [
            {
                title: 'Working Hours & Shifts',
                formFields: [
                    {
                        label: 'Working Hours per Day',
                        name: 'working_hours_per_day',
                        inputType: 'number',
                        placeholder: 'Hours',
                        require: true,
                        classStyle: 'col-span-1',
                        min: 1,
                        max: 24,
                        validation: {
                            required: 'Working hours per day is required',
                            validate: (value) => {
                                return (value >= 1 && value <= 24) || 'Must be between 1 and 24 hours';
                            },
                        },
                    },
                    {
                        label: 'Number of Shifts',
                        name: 'number_of_shifts',
                        inputType: 'select',
                        optionList: 'shiftOptions',
                        displayKey: 'label',
                        uniqueKey: 'value',
                        require: true,
                        classStyle: 'col-span-1',
                        validation: { required: 'Number of shifts is required' },
                    },
                ],
            },
            {
                title: 'Shift Details',
                formFields: [
                    {
                        label: '1st Shift Start',
                        name: 'shift_1_start',
                        inputType: 'time',
                        require: false,
                        classStyle: 'col-span-1',
                        condition: (state) => state.number_of_shifts >= 1,
                    },
                    {
                        label: '1st Shift End',
                        name: 'shift_1_end',
                        inputType: 'time',
                        require: false,
                        classStyle: 'col-span-1',
                        condition: (state) => state.number_of_shifts >= 1,
                    },
                    {
                        label: '2nd Shift Start',
                        name: 'shift_2_start',
                        inputType: 'time',
                        require: false,
                        classStyle: 'col-span-1',
                        condition: (state) => state.number_of_shifts >= 2,
                    },
                    {
                        label: '2nd Shift End',
                        name: 'shift_2_end',
                        inputType: 'time',
                        require: false,
                        classStyle: 'col-span-1',
                        condition: (state) => state.number_of_shifts >= 2,
                    },
                    {
                        label: '3rd Shift Start',
                        name: 'shift_3_start',
                        inputType: 'time',
                        require: false,
                        classStyle: 'col-span-1',
                        condition: (state) => state.number_of_shifts >= 3,
                    },
                    {
                        label: '3rd Shift End',
                        name: 'shift_3_end',
                        inputType: 'time',
                        require: false,
                        classStyle: 'col-span-1',
                        condition: (state) => state.number_of_shifts >= 3,
                    },
                    {
                        label: 'General Shift Start',
                        name: 'general_shift_start',
                        inputType: 'time',
                        require: false,
                        classStyle: 'col-span-1',
                    },
                    {
                        label: 'General Shift End',
                        name: 'general_shift_end',
                        inputType: 'time',
                        require: false,
                        classStyle: 'col-span-1',
                    },
                ],
            },
            {
                title: 'Leave & Off Days',
                formFields: [
                    {
                        label: 'Weekly Off Day',
                        name: 'weekly_off_day',
                        inputType: 'select',
                        optionList: 'weekDays',
                        displayKey: 'label',
                        uniqueKey: 'value',
                        require: true,
                        classStyle: 'col-span-1',
                        validation: { required: 'Weekly off day is required' },
                    },
                    {
                        label: 'Number of Holidays per Year',
                        name: 'holidays_per_year',
                        inputType: 'number',
                        placeholder: 'Total annual holidays',
                        require: true,
                        classStyle: 'col-span-1',
                        min: 0,
                        validation: { required: 'Number of holidays is required' },
                    },
                    {
                        label: 'Permissible Leave per Year (per employee)',
                        name: 'permissible_leave_per_year',
                        inputType: 'number',
                        placeholder: 'Leave days per employee',
                        require: true,
                        classStyle: 'col-span-1',
                        min: 0,
                        validation: { required: 'Permissible leave is required' },
                    },
                    {
                        label: 'Leave Type',
                        name: 'leave_type',
                        inputType: 'select',
                        optionList: 'leaveTypes',
                        displayKey: 'label',
                        uniqueKey: 'value',
                        require: true,
                        classStyle: 'col-span-1',
                        validation: { required: 'Leave type is required' },
                    },
                    {
                        label: 'Max OT Hours per Week',
                        name: 'max_ot_hours_per_week',
                        inputType: 'number',
                        placeholder: 'Maximum overtime hours',
                        require: false,
                        classStyle: 'col-span-1',
                        min: 0,
                    },
                ],
            },
        ],
    },
    {
        label: 'Compliance & Safety',
        name: 'complianceSafety',
        icon: <IconShield />,
        accordianStyle: 'grid lg:grid-cols-2 grid-cols-1 gap-6',
        children: [
            {
                title: 'Licenses & Registrations',
                formFields: [
                    {
                        label: 'Factory License Number',
                        name: 'factory_license_number',
                        inputType: 'text',
                        placeholder: 'Factory license number',
                        require: true,
                        classStyle: 'col-span-1',
                        validation: { required: 'Factory license number is required' },
                    },
                    {
                        label: 'Factory License Validity',
                        name: 'factory_license_validity',
                        inputType: 'date',
                        require: true,
                        classStyle: 'col-span-1',
                        validation: { required: 'Factory license validity is required' },
                    },
                    {
                        label: 'PF Number',
                        name: 'pf_number',
                        inputType: 'text',
                        placeholder: 'Provident Fund number',
                        require: true,
                        classStyle: 'col-span-1',
                        validation: { required: 'PF number is required' },
                    },
                    {
                        label: 'Last PF Challan Paid',
                        name: 'last_pf_challan_paid',
                        inputType: 'month',
                        require: true,
                        classStyle: 'col-span-1',
                        validation: { required: 'Last PF challan paid is required' },
                    },
                    {
                        label: 'ESI Number',
                        name: 'esi_number',
                        inputType: 'text',
                        placeholder: 'Employee State Insurance number',
                        require: true,
                        classStyle: 'col-span-1',
                        validation: { required: 'ESI number is required' },
                    },
                    {
                        label: 'Last ESI Challan Paid',
                        name: 'last_esi_challan_paid',
                        inputType: 'month',
                        require: true,
                        classStyle: 'col-span-1',
                        validation: { required: 'Last ESI challan paid is required' },
                    },
                    {
                        label: 'TNPCB Air Consent Number',
                        name: 'tnpcb_air_consent',
                        inputType: 'text',
                        placeholder: 'Air consent number',
                        require: false,
                        classStyle: 'col-span-1',
                    },
                    {
                        label: 'TNPCB Air Consent Validity',
                        name: 'tnpcb_air_validity',
                        inputType: 'date',
                        require: false,
                        classStyle: 'col-span-1',
                    },
                    {
                        label: 'TNPCB Water Consent Number',
                        name: 'tnpcb_water_consent',
                        inputType: 'text',
                        placeholder: 'Water consent number',
                        require: false,
                        classStyle: 'col-span-1',
                    },
                    {
                        label: 'TNPCB Water Consent Validity',
                        name: 'tnpcb_water_validity',
                        inputType: 'date',
                        require: false,
                        classStyle: 'col-span-1',
                    },
                    {
                        label: 'PCB Industry Category',
                        name: 'pcb_industry_category',
                        inputType: 'text',
                        placeholder: 'PCB category',
                        require: false,
                        classStyle: 'col-span-2',
                    },
                ],
            },
            {
                title: 'Facility & Safety',
                formFields: [
                    {
                        label: 'Clean Drinking Water Points',
                        name: 'drinking_water_points',
                        inputType: 'number',
                        placeholder: 'Number of water points',
                        require: true,
                        classStyle: 'col-span-1',
                        min: 1,
                        validation: { required: 'Drinking water points are required' },
                    },
                    {
                        label: 'Toilets - Male Count',
                        name: 'toilets_male',
                        inputType: 'number',
                        placeholder: 'Male toilets',
                        require: true,
                        classStyle: 'col-span-1',
                        min: 1,
                        validation: { required: 'Male toilets count is required' },
                    },
                    {
                        label: 'Toilets - Female Count',
                        name: 'toilets_female',
                        inputType: 'number',
                        placeholder: 'Female toilets',
                        require: true,
                        classStyle: 'col-span-1',
                        min: 1,
                        validation: { required: 'Female toilets count is required' },
                    },
                    {
                        label: 'Windows/Exit Doors',
                        name: 'windows_exit_doors',
                        inputType: 'number',
                        placeholder: 'Number of exits',
                        require: true,
                        classStyle: 'col-span-1',
                        min: 1,
                        validation: { required: 'Windows/exit doors count is required' },
                    },
                    {
                        label: 'Safety Equipment Available',
                        name: 'safety_equipment',
                        inputType: 'checkboxGroup',
                        options: [
                            { label: 'Fire Extinguishers', value: 'fire_extinguishers' },
                            { label: 'First Aid Boxes', value: 'first_aid_boxes' },
                            { label: 'Emergency Lights', value: 'emergency_lights' },
                            { label: 'Smoke Detectors', value: 'smoke_detectors' },
                        ],
                        require: true,
                        classStyle: 'col-span-2',
                        validation: { required: 'Select safety equipment available' },
                    },
                    {
                        label: 'Accident in Past Year',
                        name: 'accident_past_year',
                        inputType: 'radio',
                        optionList: 'yesNoOptions',
                        displayKey: 'label',
                        uniqueKey: 'value',
                        require: true,
                        classStyle: 'col-span-1',
                        validation: { required: 'Please specify if accident occurred' },
                    },
                    {
                        label: 'Accident Recorded in Register',
                        name: 'accident_recorded',
                        inputType: 'radio',
                        optionList: 'yesNoOptions',
                        displayKey: 'label',
                        uniqueKey: 'value',
                        require: false,
                        classStyle: 'col-span-1',
                        condition: (state) => state.accident_past_year === 'yes',
                    },
                    {
                        label: 'Safety Devices & PPEs Provided',
                        name: 'safety_devices_provided',
                        inputType: 'radio',
                        optionList: 'yesNoOptions',
                        displayKey: 'label',
                        uniqueKey: 'value',
                        require: true,
                        classStyle: 'col-span-1',
                        validation: { required: 'Please specify if safety devices are provided' },
                    },
                    {
                        label: 'PPE Types & Numbers',
                        name: 'ppe_types_numbers',
                        inputType: 'textarea',
                        placeholder: 'List PPE types and quantities',
                        require: false,
                        rows: 2,
                        classStyle: 'col-span-2',
                        condition: (state) => state.safety_devices_provided === 'yes',
                    },
                    {
                        label: 'ETP (Effluent Treatment Plant)',
                        name: 'etp_available',
                        inputType: 'radio',
                        optionList: 'yesNoOptions',
                        displayKey: 'label',
                        uniqueKey: 'value',
                        require: false,
                        classStyle: 'col-span-1',
                    },
                    {
                        label: 'ETP Capacity',
                        name: 'etp_capacity',
                        inputType: 'text',
                        placeholder: 'Water treatment capacity',
                        require: false,
                        classStyle: 'col-span-1',
                        condition: (state) => state.etp_available === 'yes',
                    },
                ],
            },
        ],
    },
    {
        label: 'Labor & Standards',
        name: 'laborStandards',
        icon: <IconScale />,
        accordianStyle: 'grid lg:grid-cols-2 grid-cols-1 gap-6',
        children: [
            {
                title: 'Labor Practices',
                formFields: [
                    {
                        label: 'Recognized Trade Union',
                        name: 'trade_union',
                        inputType: 'radio',
                        optionList: 'yesNoOptions',
                        displayKey: 'label',
                        uniqueKey: 'value',
                        require: true,
                        classStyle: 'col-span-1',
                        validation: { required: 'Please specify about trade union' },
                    },
                    {
                        label: 'Grievance Communication Method',
                        name: 'grievance_communication',
                        inputType: 'textarea',
                        placeholder: 'How workers communicate grievances',
                        require: false,
                        rows: 2,
                        classStyle: 'col-span-2',
                        condition: (state) => state.trade_union === 'no',
                    },
                    {
                        label: 'Recruitment Preferences',
                        name: 'recruitment_preferences',
                        inputType: 'checkboxGroup',
                        options: [
                            { label: 'Caste', value: 'caste' },
                            { label: 'Gender', value: 'gender' },
                            { label: 'Disability', value: 'disability' },
                            { label: 'Political Affiliation', value: 'political' },
                            { label: 'Religion', value: 'religion' },
                            { label: 'None', value: 'none' },
                        ],
                        require: true,
                        classStyle: 'col-span-2',
                        validation: { required: 'Select recruitment preferences' },
                    },
                    {
                        label: 'Preference Reasons',
                        name: 'preference_reasons',
                        inputType: 'textarea',
                        placeholder: 'Reasons for preferences',
                        require: false,
                        rows: 2,
                        classStyle: 'col-span-2',
                        condition: (state) => state.recruitment_preferences && !state.recruitment_preferences.includes('none') && state.recruitment_preferences.length > 0,
                    },
                    {
                        label: 'Wages as per Minimum Wages Act',
                        name: 'minimum_wages_act',
                        inputType: 'radio',
                        optionList: 'yesNoOptions',
                        displayKey: 'label',
                        uniqueKey: 'value',
                        require: true,
                        classStyle: 'col-span-1',
                        validation: { required: 'Please specify about minimum wages' },
                    },
                    {
                        label: 'Time Recording System',
                        name: 'time_recording_system',
                        inputType: 'select',
                        optionList: 'timeRecordingSystems',
                        displayKey: 'label',
                        uniqueKey: 'value',
                        require: true,
                        classStyle: 'col-span-1',
                        validation: { required: 'Time recording system is required' },
                    },
                    {
                        label: 'Pay Slips Provided',
                        name: 'pay_slips_provided',
                        inputType: 'radio',
                        optionList: 'yesNoOptions',
                        displayKey: 'label',
                        uniqueKey: 'value',
                        require: true,
                        classStyle: 'col-span-1',
                        validation: { required: 'Please specify about pay slips' },
                    },
                    {
                        label: 'Accommodation Facility',
                        name: 'accommodation_facility',
                        inputType: 'radio',
                        optionList: 'yesNoOptions',
                        displayKey: 'label',
                        uniqueKey: 'value',
                        require: true,
                        classStyle: 'col-span-1',
                        validation: { required: 'Please specify about accommodation facility' },
                    },
                    {
                        label: 'Accommodation Details',
                        name: 'accommodation_details',
                        inputType: 'textarea',
                        placeholder: 'For Male/Female/Family, specify...',
                        require: false,
                        rows: 2,
                        classStyle: 'col-span-2',
                        condition: (state) => state.accommodation_facility === 'yes',
                    },
                    {
                        label: 'Accommodation Separate from Factory',
                        name: 'accommodation_separate',
                        inputType: 'radio',
                        optionList: 'yesNoOptions',
                        displayKey: 'label',
                        uniqueKey: 'value',
                        require: false,
                        classStyle: 'col-span-1',
                        condition: (state) => state.accommodation_facility === 'yes',
                    },
                    {
                        label: 'Residents Allowed to Go Out',
                        name: 'residents_allowed_out',
                        inputType: 'radio',
                        optionList: 'yesNoOptions',
                        displayKey: 'label',
                        uniqueKey: 'value',
                        require: false,
                        classStyle: 'col-span-1',
                        condition: (state) => state.accommodation_facility === 'yes',
                    },
                ],
            },
            {
                title: 'Worker Documentation',
                formFields: [
                    {
                        label: 'Age Proof Documents Available',
                        name: 'age_proof_documents',
                        inputType: 'radio',
                        optionList: 'yesNoOptions',
                        displayKey: 'label',
                        uniqueKey: 'value',
                        require: true,
                        classStyle: 'col-span-1',
                        validation: { required: 'Please specify about age proof documents' },
                    },
                    {
                        label: 'Appointment Orders Given',
                        name: 'appointment_orders_given',
                        inputType: 'radio',
                        optionList: 'yesNoOptions',
                        displayKey: 'label',
                        uniqueKey: 'value',
                        require: true,
                        classStyle: 'col-span-1',
                        validation: { required: 'Please specify about appointment orders' },
                    },
                    {
                        label: 'Young Workers Employed',
                        name: 'young_workers_employed',
                        inputType: 'radio',
                        optionList: 'yesNoOptions',
                        displayKey: 'label',
                        uniqueKey: 'value',
                        require: true,
                        classStyle: 'col-span-1',
                        validation: { required: 'Please specify about young workers' },
                    },
                    {
                        label: 'Form V Available',
                        name: 'form_v_available',
                        inputType: 'radio',
                        optionList: 'yesNoOptions',
                        displayKey: 'label',
                        uniqueKey: 'value',
                        require: false,
                        classStyle: 'col-span-1',
                        condition: (state) => state.young_workers_employed === 'yes',
                    },
                    {
                        label: 'Jobs for Young Workers',
                        name: 'young_worker_jobs',
                        inputType: 'textarea',
                        placeholder: 'Describe jobs assigned to young workers',
                        require: false,
                        rows: 2,
                        classStyle: 'col-span-2',
                        condition: (state) => state.young_workers_employed === 'yes',
                    },
                    {
                        label: 'Bonded or Forced Labor',
                        name: 'bonded_labor',
                        inputType: 'radio',
                        optionList: 'yesNoOptions',
                        displayKey: 'label',
                        uniqueKey: 'value',
                        require: true,
                        classStyle: 'col-span-1',
                        validation: { required: 'Please specify about bonded labor' },
                    },
                    {
                        label: 'Loans or Advances Given',
                        name: 'loans_advances_given',
                        inputType: 'radio',
                        optionList: 'yesNoOptions',
                        displayKey: 'label',
                        uniqueKey: 'value',
                        require: true,
                        classStyle: 'col-span-1',
                        validation: { required: 'Please specify about loans/advances' },
                    },
                    {
                        label: 'Disciplinary Procedures Available',
                        name: 'disciplinary_procedures',
                        inputType: 'radio',
                        optionList: 'yesNoOptions',
                        displayKey: 'label',
                        uniqueKey: 'value',
                        require: true,
                        classStyle: 'col-span-1',
                        validation: { required: 'Please specify about disciplinary procedures' },
                    },
                    {
                        label: 'Approved Standing Orders',
                        name: 'standing_orders',
                        inputType: 'radio',
                        optionList: 'yesNoOptions',
                        displayKey: 'label',
                        uniqueKey: 'value',
                        require: true,
                        classStyle: 'col-span-1',
                        validation: { required: 'Please specify about standing orders' },
                    },
                ],
            },
            {
                title: 'Policies',
                formFields: [
                    {
                        label: 'Anti-Corruption Policy',
                        name: 'anti_corruption_policy',
                        inputType: 'radio',
                        optionList: 'yesNoOptions',
                        displayKey: 'label',
                        uniqueKey: 'value',
                        require: true,
                        classStyle: 'col-span-1',
                        validation: { required: 'Please specify about anti-corruption policy' },
                    },
                    {
                        label: 'Anti-Alcohol/Drugs Policy',
                        name: 'anti_alcohol_drugs_policy',
                        inputType: 'radio',
                        optionList: 'yesNoOptions',
                        displayKey: 'label',
                        uniqueKey: 'value',
                        require: true,
                        classStyle: 'col-span-1',
                        validation: { required: 'Please specify about anti-alcohol/drugs policy' },
                    },
                    {
                        label: 'Recruitment Agencies Used',
                        name: 'recruitment_agencies_used',
                        inputType: 'radio',
                        optionList: 'yesNoOptions',
                        displayKey: 'label',
                        uniqueKey: 'value',
                        require: true,
                        classStyle: 'col-span-1',
                        validation: { required: 'Please specify about recruitment agencies' },
                    },
                    {
                        label: 'Contracts Signed with Agencies',
                        name: 'agency_contracts_signed',
                        inputType: 'radio',
                        optionList: 'yesNoOptions',
                        displayKey: 'label',
                        uniqueKey: 'value',
                        require: false,
                        classStyle: 'col-span-1',
                        condition: (state) => state.recruitment_agencies_used === 'yes',
                    },
                ],
            },
        ],
    },
    {
        label: 'Customer Standards',
        name: 'customerStandards',
        icon: <IconDocument />,
        accordianStyle: 'grid lg:grid-cols-2 grid-cols-1 gap-6',
        children: [
            {
                title: 'Accepted Standards',
                formFields: [
                    {
                        label: 'Customer Standards (Add Multiple)',
                        name: 'customer_standards',
                        inputType: 'multiAdd',
                        fields: [
                            {
                                label: 'Standard Name',
                                name: 'standard_name',
                                inputType: 'text',
                                placeholder: 'e.g., IWAY Standard 6.0',
                                require: true,
                            },
                            {
                                label: 'Date of Acceptance',
                                name: 'acceptance_date',
                                inputType: 'date',
                                require: true,
                            },
                            {
                                label: 'Standard Version',
                                name: 'standard_version',
                                inputType: 'text',
                                placeholder: 'e.g., 6.0',
                                require: false,
                            },
                        ],
                        require: false,
                        classStyle: 'col-span-2',
                    },
                    {
                        label: 'Specific Company Policies',
                        name: 'specific_policies',
                        inputType: 'textarea',
                        placeholder: 'List any specific company policies followed',
                        require: false,
                        rows: 3,
                        classStyle: 'col-span-2',
                    },
                ],
            },
            {
                title: 'Compliance Documents',
                formFields: [
                    {
                        label: 'Upload Compliance Certificates',
                        name: 'compliance_certificates',
                        inputType: 'file',
                        require: false,
                        multiple: true,
                        accept: '.pdf,.jpg,.jpeg,.png',
                        classStyle: 'col-span-2',
                        validation: {
                            validate: (files) => {
                                if (!files || files.length === 0) return true;
                                const maxSize = 5 * 1024 * 1024; // 5MB
                                for (let file of files) {
                                    if (file.size > maxSize) {
                                        return 'File size must be less than 5MB';
                                    }
                                }
                                return true;
                            },
                        },
                    },
                    {
                        label: 'Last Audit Date',
                        name: 'last_audit_date',
                        inputType: 'date',
                        require: false,
                        classStyle: 'col-span-1',
                    },
                    {
                        label: 'Next Audit Date',
                        name: 'next_audit_date',
                        inputType: 'date',
                        require: false,
                        classStyle: 'col-span-1',
                    },
                    {
                        label: 'Audit Score (%)',
                        name: 'audit_score',
                        inputType: 'number',
                        placeholder: 'Last audit score',
                        require: false,
                        classStyle: 'col-span-1',
                        min: 0,
                        max: 100,
                    },
                    {
                        label: 'Auditor Name',
                        name: 'auditor_name',
                        inputType: 'text',
                        placeholder: 'Auditor/Company name',
                        require: false,
                        classStyle: 'col-span-1',
                    },
                ],
            },
        ],
    },
];

// Enhanced option lists with categories
const optionLists = {
    ownershipTypes: [
        { value: 'fully_owned', label: 'Fully Owned', color: 'text-emerald-600', bgColor: 'bg-emerald-100' },
        { value: 'joint_venture', label: 'Joint Venture', color: 'text-blue-600', bgColor: 'bg-blue-100' },
        { value: 'partnership', label: 'Partnership', color: 'text-purple-600', bgColor: 'bg-purple-100' },
        { value: 'private_limited', label: 'Private Limited', color: 'text-amber-600', bgColor: 'bg-amber-100' },
        { value: 'public_limited', label: 'Public Limited', color: 'text-rose-600', bgColor: 'bg-rose-100' },
        { value: 'proprietorship', label: 'Proprietorship', color: 'text-indigo-600', bgColor: 'bg-indigo-100' },
    ],

    supplierCategories: [
        { value: 'wet_processing', label: 'Wet Processing', color: 'text-blue-600', bgColor: 'bg-blue-100' },
        { value: 'dyeing', label: 'Dyeing', color: 'text-indigo-600', bgColor: 'bg-indigo-100' },
        { value: 'printing', label: 'Printing', color: 'text-purple-600', bgColor: 'bg-purple-100' },
        { value: 'weaving', label: 'Weaving', color: 'text-emerald-600', bgColor: 'bg-emerald-100' },
        { value: 'spinning', label: 'Spinning', color: 'text-amber-600', bgColor: 'bg-amber-100' },
        { value: 'finishing', label: 'Finishing', color: 'text-rose-600', bgColor: 'bg-rose-100' },
        { value: 'garment', label: 'Garment Manufacturing', color: 'text-pink-600', bgColor: 'bg-pink-100' },
        { value: 'accessories', label: 'Accessories', color: 'text-cyan-600', bgColor: 'bg-cyan-100' },
    ],

    // Add more with similar styling
};

// Modern static supplier data
const staticSuppliersData = [
    {
        id: 1,
        supplier_id: 'SUP-001',
        supplier_name: 'Asian Fabrics Private Limited',
        category: 'Wet Processing',
        supplier_code: 'GRS123',
        address: '54, L.B.4, N23AY, KAYAY',
        city: 'Kayay',
        postal_code: '600001',
        contact_person: 'Key Blazer',
        designation: 'General Manager',
        mobile_number: '7800000156',
        email: 'info@asianfabrics.com',
        status: 'active',
        kyc_status: 'verified',
        last_audit_date: '2025-12-15',
        next_audit_date: '2026-06-15',
        branch_name: 'Main Branch',
        branch_id: 'BR-001',
        logo: 'https://via.placeholder.com/150',
        rating: 4.5,
        compliance_score: 85,
    },
    // ... Add more with enhanced structure
];

// Badge styling functions
const getStatusBadge = (status) => {
    const badges = {
        active: {
            text: 'Active',
            color: 'bg-emerald-100 text-emerald-800 border-emerald-200',
            icon: '🟢',
        },
        inactive: {
            text: 'Inactive',
            color: 'bg-gray-100 text-gray-800 border-gray-200',
            icon: '⚫',
        },
        pending: {
            text: 'Pending',
            color: 'bg-amber-100 text-amber-800 border-amber-200',
            icon: '🟡',
        },
        suspended: {
            text: 'Suspended',
            color: 'bg-rose-100 text-rose-800 border-rose-200',
            icon: '🔴',
        },
    };
    return badges[status] || badges.inactive;
};

const getKycBadge = (status) => {
    const badges = {
        verified: {
            text: 'Verified',
            color: 'bg-emerald-100 text-emerald-800 border-emerald-200',
            icon: '✅',
        },
        pending: {
            text: 'Pending',
            color: 'bg-amber-100 text-amber-800 border-amber-200',
            icon: '⏳',
        },
        rejected: {
            text: 'Rejected',
            color: 'bg-rose-100 text-rose-800 border-rose-200',
            icon: '❌',
        },
        in_progress: {
            text: 'In Progress',
            color: 'bg-blue-100 text-blue-800 border-blue-200',
            icon: '🔄',
        },
    };
    return badges[status] || badges.pending;
};

const getAuditBadge = (score) => {
    if (score >= 90)
        return {
            text: 'Excellent',
            color: 'bg-emerald-100 text-emerald-800 border-emerald-200',
            icon: '🏆',
        };
    if (score >= 80)
        return {
            text: 'Good',
            color: 'bg-blue-100 text-blue-800 border-blue-200',
            icon: '👍',
        };
    if (score >= 70)
        return {
            text: 'Fair',
            color: 'bg-amber-100 text-amber-800 border-amber-200',
            icon: '⚠️',
        };
    return {
        text: 'Poor',
        color: 'bg-rose-100 text-rose-800 border-rose-200',
        icon: '📉',
    };
};

export { supplierTabs, optionLists, staticSuppliersData, getStatusBadge, getKycBadge, getAuditBadge };
